### ISSUE TITLE
Initial Task List

### ISSUE THREAD

**Issue by micheltakken** [cda-tum/mmft-simulator#1]
The following issues were known at the time of first commit and will be fixed in following updates according to their priority.

- [x] Add (unit) tests and increase code coverage
- [x] Add function to set relaxation factor, resolution and convergence criterion (CFD-1D) #4 
- [x] Add addNode(), addChannel(), addLbmModule() functions for dynamics network definition
- [x] Add a function to check network validity
- [ ] Add check for highest lattice Mach number for incompressibility assumption
- [ ] Keep track of memory requirement for the CFD modules
- [x] Add setFlowRate() and readPressure() functionality for CFD modules #4 
- [x] Remove boilerplate code in NodalAnalysis
- [ ] Add 3D CFD modules
- [x] Complete documentation/comments #4 
- [ ] Port to OpenLB v1.7
- [ ] Add python wheels for Windows
- [x] Add references in Readme
